/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package R_BT_B;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

class StructureSeedThread extends Thread {
    public static long START_SEED;
    public static long END_SEED;
    public int threadCount;
    public int offset;

    StructureSeedThread(int threadCount, int offset) {
        this.threadCount = threadCount;
        this.offset = offset;
    }

    public void run()
    {
        try {
            System.out.println(
                    "Thread " + Thread.currentThread().getId()
                            + " is running");

            StructureSeedFilter.filterStructureSeeds(this.threadCount, this.offset, START_SEED, END_SEED);
        }
        catch (Exception e) {
            System.out.println("Exception is caught");
        }
    }
}


public class App {

    public static final String OPTIONS_PATHNAME = "options.txt";
    public static final String STRUCTURE_SEEDS_PATHNAME = "output-structureSeeds.txt";

    public static int THREAD_COUNT;

    public static void createThread(int t) throws InterruptedException {
        if (t < THREAD_COUNT - 1) {
            Runnable structureSeedThread = new StructureSeedThread(THREAD_COUNT, t);
            Thread thread = new Thread(structureSeedThread);
            thread.start();
            t++;
            createThread(t);
            thread.join();
        } else {
            Runnable structureSeedThread = new StructureSeedThread(THREAD_COUNT, t);
            Thread thread = new Thread(structureSeedThread);
            thread.start();
            thread.join();
        }
    }

    public static void main(String[] args) throws InterruptedException {
        try {
            File file = new File(OPTIONS_PATHNAME);
            Scanner reader = new Scanner(file);
            StructureSeedThread.START_SEED = Long.parseLong(reader.nextLine());
            StructureSeedThread.END_SEED = Long.parseLong(reader.nextLine());
            THREAD_COUNT = Integer.parseInt(reader.nextLine());
            reader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }

        StructureSeedFilter.filteredSeeds.clear();
        int t = 0;
        createThread(t);

        try {
            FileWriter writer = new FileWriter(STRUCTURE_SEEDS_PATHNAME);
            for (long filteredSeed : StructureSeedFilter.filteredSeeds) {
                writer.write(filteredSeed + "\n");
            }
            writer.close();
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }
}
